# Generated by Django 5.2 on 2025-04-06 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_federativa', models.CharField(default='Ciudad de México', max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('municipio_alcaldia', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=255)),
                ('num_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('num_int', models.CharField(blank=True, max_length=10, null=True)),
                ('entre_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('y_calle', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, choices=[('Banqueta', 'Banqueta'), ('Camellón', 'Camellón'), ('Glorieta', 'Glorieta'), ('Parque', 'Parque'), ('Arriate', 'Arriate'), ('Plaza', 'Plaza'), ('Propiedad privada', 'Propiedad privada'), ('Obra civil', 'Obra civil'), ('Otro', 'Otro')], max_length=50)),
                ('ubicacion_otro', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('numero_arbol', models.CharField(blank=True, max_length=50, null=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diametro_tronco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diametro_copa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inclinacion_tronco', models.CharField(max_length=50)),
                ('estructura_general', models.CharField(choices=[('copa mal equilibrada', 'Copa mal equilibrada'), ('ramas muy largas', 'Ramas muy largas'), ('troncos múltiples', 'Troncos múltiples'), ('troncos codominantes', 'Troncos codominantes'), ('ramas codominantes', 'Ramas codominantes')], max_length=50)),
                ('condicion_general', models.CharField(choices=[('irrecuperable', 'Irrecuperable'), ('susceptible de mejora', 'Susceptible de mejora'), ('buena', 'Buena'), ('muy buena', 'Muy buena')], max_length=50)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('foto1', models.ImageField(upload_to='arboles/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='arboles/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='arboles/')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='arboles/')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='arboles/')),
            ],
        ),
    ]
