# Generated by Django 4.2.11 on 2025-06-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='foto1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='foto2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='foto3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='foto4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbol',
            name='foto5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
