# Generated by Django 4.2.11 on 2025-06-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0002_alter_arbol_foto1_alter_arbol_foto2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbol',
            name='foto1',
        ),
    ]
