# Generated by Django 4.2.11 on 2025-06-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0003_remove_arbol_foto1'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbol',
            name='foto1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
