# Generated by Django 4.2.11 on 2025-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0005_alter_arbol_foto1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbol',
            name='estructura_general',
            field=models.JSONField(blank=True, default=list, help_text='Estructuras problemáticas del árbol'),
        ),
        migrations.AddIndex(
            model_name='arbol',
            index=models.Index(fields=['latitud', 'longitud'], name='arbol_arbol_latitud_fd64c0_idx'),
        ),
    ]
