# Generated by Django 4.2.11 on 2025-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbol', '0006_alter_arbol_estructura_general_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='arbol',
            name='arbol_arbol_latitud_fd64c0_idx',
        ),
        migrations.AddConstraint(
            model_name='arbol',
            constraint=models.UniqueConstraint(fields=('latitud', 'longitud'), name='coordenadas_unicas'),
        ),
    ]
