app = "urbanatura-cdmx"

[build]
  dockerfile = "Dockerfile"
[env]
  DJANGO_SETTINGS_MODULE = "urbanatura_cdmx.settings"
  PYTHONUNBUFFERED = "1"
  STATIC_URL = "/static/"
  STATIC_ROOT = "/static"
  
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0