app = "urbanatura-cdmx"

[build]
  dockerfile = "Dockerfile"
  context = "backend"


[env]
  DJANGO_SETTINGS_MODULE = "urbanatura_cdmx.settings"
  PYTHONUNBUFFERED = "1"
  STATIC_URL = "/static/"
  DEBUG = "False"
  
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20
