# Generated by Django 4.2.11 on 2025-06-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, default=19.4326, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, default=-99.1332, max_digits=9)),
                ('motivo_poda', models.CharField(choices=[('mantenimiento', 'Mantenimiento preventivo'), ('seguridad', 'Seguridad (ramas peligrosas)'), ('salud', 'Salud del árbol'), ('interferencia', 'Interferencia con infraestructura')], max_length=20)),
                ('foto_poda', models.ImageField(upload_to='poda/')),
                ('ubicacion_poda', models.CharField(choices=[('banqueta', 'Banqueta'), ('camellon', 'Camellón'), ('glorieta', 'Glorieta'), ('parque', 'Parque')], max_length=20)),
                ('calle_poda', models.CharField(max_length=100)),
                ('numero_ext_poda', models.CharField(max_length=10)),
                ('numero_int_poda', models.CharField(blank=True, max_length=10, null=True)),
                ('alcaldia_poda', models.CharField(max_length=50)),
                ('colonia_poda', models.CharField(max_length=50)),
                ('cp_poda', models.CharField(max_length=5)),
                ('referencias_poda', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Solicitud de Poda',
                'verbose_name_plural': 'Solicitudes de Poda',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
