# Generated by Django 4.2.11 on 2025-06-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poda', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpoda',
            name='motivo_poda',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento preventivo'), ('seguridad', 'Seguridad (ramas peligrosas)'), ('salud', 'Salud del árbol'), ('interferencia', 'Interferencia con infraestructura'), ('poda_livia', 'Poda liviana (ramas pequeñas)'), ('poda_media', 'Poda media (ramas medianas)'), ('poda_fuerte', 'Poda fuerte (ramas grandes)'), ('poda_tecnia', 'Poda técnica (especializada)')], max_length=20),
        ),
    ]
