# Generated by Django 4.2.11 on 2025-06-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poda', '0003_alter_solicitudpoda_motivo_poda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpoda',
            name='foto_poda',
            field=models.TextField(verbose_name='Imagen del árbol en Base64'),
        ),
    ]
