# Generated by Django 4.2.11 on 2025-06-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poda', '0004_alter_solicitudpoda_foto_poda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpoda',
            name='alcaldia_poda',
            field=models.CharField(max_length=60, verbose_name='Alcaldía'),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='calle_poda',
            field=models.CharField(max_length=120, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='colonia_poda',
            field=models.CharField(max_length=120, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='cp_poda',
            field=models.CharField(max_length=5, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='motivo_poda',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento preventivo'), ('seguridad', 'Seguridad (ramas peligrosas)'), ('salud', 'Salud del árbol'), ('interferencia', 'Interferencia con infraestructura')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='numero_ext_poda',
            field=models.CharField(max_length=10, verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='numero_int_poda',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número interior'),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='referencias_poda',
            field=models.TextField(blank=True, verbose_name='Referencias adicionales'),
        ),
        migrations.AlterField(
            model_name='solicitudpoda',
            name='ubicacion_poda',
            field=models.CharField(choices=[('banqueta', 'Banqueta'), ('camellon', 'Camellón'), ('glorieta', 'Glorieta'), ('parque', 'Parque'), ('arriate', 'Arriate'), ('plaza', 'Plaza'), ('propiedad_privada', 'Propiedad privada')], max_length=20),
        ),
    ]
