# Generated by Django 4.2.11 on 2025-06-29 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trasplante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtraslado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_traslado', to=settings.AUTH_USER_MODEL),
        ),
    ]
