# Generated by Django 5.1.6 on 2025-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='arboles/')),
                ('calle', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('delegacion', models.CharField(max_length=100)),
                ('ciudad', models.CharField(default='Ciudad de México', max_length=100)),
                ('estado', models.CharField(default='Ciudad de México', max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tiene_plaga', models.BooleanField(default=False)),
            ],
        ),
    ]
