# Generated by Django 4.2.11 on 2025-06-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDerribo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, default=19.4326, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, default=-99.1332, max_digits=9)),
                ('motivo_derribo', models.CharField(choices=[('riesgo', 'Riesgo de caída'), ('enfermedad', 'Enfermedad irreversible'), ('construccion', 'Para construcción'), ('obstruccion', 'Obstrucción grave'), ('otro', 'Otro motivo')], max_length=20)),
                ('foto_derribo', models.ImageField(upload_to='derribo/')),
                ('ubicacion_derribo', models.CharField(choices=[('banqueta', 'Banqueta'), ('camellon', 'Camellón'), ('propiedad_privada', 'Propiedad privada'), ('area_publica', 'Área pública')], max_length=20)),
                ('calle_derribo', models.CharField(max_length=100)),
                ('numero_ext_derribo', models.CharField(max_length=10)),
                ('numero_int_derribo', models.CharField(blank=True, max_length=10, null=True)),
                ('alcaldia_derribo', models.CharField(max_length=50)),
                ('colonia_derribo', models.CharField(max_length=50)),
                ('cp_derribo', models.CharField(max_length=5)),
                ('justificacion_derribo', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('requiere_aprobacion', 'Requiere aprobación especial')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Solicitud de Derribo',
                'verbose_name_plural': 'Solicitudes de Derribo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
