# Generated by Django 4.2.11 on 2025-06-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('derribo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudderribo',
            name='alcaldia_derribo',
            field=models.CharField(max_length=60, verbose_name='Alcaldía'),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='calle_derribo',
            field=models.CharField(max_length=120, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='colonia_derribo',
            field=models.CharField(max_length=120, verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='cp_derribo',
            field=models.CharField(max_length=5, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='foto_derribo',
            field=models.TextField(verbose_name='Imagen del árbol en Base64'),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='justificacion_derribo',
            field=models.TextField(verbose_name='Justificación del derribo'),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='latitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='longitud',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='numero_ext_derribo',
            field=models.CharField(max_length=10, verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='solicitudderribo',
            name='numero_int_derribo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número interior'),
        ),
    ]
